column Trasformation in Pandas

Rows and columns selections

In [18]:
import pandas as pd

In [3]:
import os
print(os.getcwd())

C:\Users\91805

In [7]:
import pandas as pd

df = pd.read_csv(r"C:\datascience\datascience-with-python\Pandas\student.csv")

print(df)

    id firstName  lastName  age  marks   fees
0  101    Akshay    Shetty   20     85  25000
1  102    Ananya       Rao   21     92  30000
2  103     Rohit  Bhandary   19     76  28000
3  104     Nisha   D'Souza   20     88  25000
4  105   Karthik   Poojary   22     69  32000
5  106    Shreya    Shetty   19     95  30000
6  107     Rohan      Naik   21     72  27000
7  108   Deepika      Bhat   20     81  28000
8  109  Abhishek    Kotian   22     64  26000
9  110     Pooja       Rai   19     90  30000

In [10]:
#Select columns
import pandas as pd

sdata = pd.read_csv(r"C:\datascience\datascience-with-python\Pandas\student.csv")
sdata[['firstName',"marks",'fees']]
#Select rows
sdata.loc[sdata.id==106]
sdata.loc[sdata.firstName=='Rohan']
#Select rows using condition
sdata.loc[sdata.age>20]
#Slicing rows
sdata.iloc[:6, :4]
sdata.iloc[2:7, 1:3]

  firstName  lastName
2     Rohit  Bhandary
3     Nisha   D'Souza
4   Karthik   Poojary
5    Shreya    Shetty
6     Rohan      Naik

In [11]:
sdata["FullName"]=sdata["firstName"]+" "+sdata["lastName"]
sdata

    id firstName  lastName  age  marks   fees         FullName
0  101    Akshay    Shetty   20     85  25000    Akshay Shetty
1  102    Ananya       Rao   21     92  30000       Ananya Rao
2  103     Rohit  Bhandary   19     76  28000   Rohit Bhandary
3  104     Nisha   D'Souza   20     88  25000    Nisha D'Souza
4  105   Karthik   Poojary   22     69  32000  Karthik Poojary
5  106    Shreya    Shetty   19     95  30000    Shreya Shetty
6  107     Rohan      Naik   21     72  27000       Rohan Naik
7  108   Deepika      Bhat   20     81  28000     Deepika Bhat
8  109  Abhishek    Kotian   22     64  26000  Abhishek Kotian
9  110     Pooja       Rai   19     90  30000        Pooja Rai

Filter

In [13]:
# Students scoring above 80
sdata[sdata['marks'] > 80]

    id firstName lastName  age  marks   fees       FullName
0  101    Akshay   Shetty   20     85  25000  Akshay Shetty
1  102    Ananya      Rao   21     92  30000     Ananya Rao
3  104     Nisha  D'Souza   20     88  25000  Nisha D'Souza
5  106    Shreya   Shetty   19     95  30000  Shreya Shetty
7  108   Deepika     Bhat   20     81  28000   Deepika Bhat
9  110     Pooja      Rai   19     90  30000      Pooja Rai

In [14]:
# Students aged 20
sdata[sdata['age'] == 20]

    id firstName lastName  age  marks   fees       FullName
0  101    Akshay   Shetty   20     85  25000  Akshay Shetty
3  104     Nisha  D'Souza   20     88  25000  Nisha D'Souza
7  108   Deepika     Bhat   20     81  28000   Deepika Bhat

In [15]:
# Students paying fees of 30000
sdata[sdata['fees'] == 30000]

    id firstName lastName  age  marks   fees       FullName
1  102    Ananya      Rao   21     92  30000     Ananya Rao
5  106    Shreya   Shetty   19     95  30000  Shreya Shetty
9  110     Pooja      Rai   19     90  30000      Pooja Rai

In [16]:
# Students scoring above 80 and paying fees below 30000
sdata[(sdata['marks'] > 80) & (sdata['fees'] < 30000)]

    id firstName lastName  age  marks   fees       FullName
0  101    Akshay   Shetty   20     85  25000  Akshay Shetty
3  104     Nisha  D'Souza   20     88  25000  Nisha D'Souza
7  108   Deepika     Bhat   20     81  28000   Deepika Bhat

In [17]:
# Select specific columns
sdata[['firstName', 'marks', 'fees']]

  firstName  marks   fees
0    Akshay     85  25000
1    Ananya     92  30000
2     Rohit     76  28000
3     Nisha     88  25000
4   Karthik     69  32000
5    Shreya     95  30000
6     Rohan     72  27000
7   Deepika     81  28000
8  Abhishek     64  26000
9     Pooja     90  30000

In [19]:
sdata.where(sdata['marks'] > 80)

      id firstName lastName   age  marks     fees       FullName
0  101.0    Akshay   Shetty  20.0   85.0  25000.0  Akshay Shetty
1  102.0    Ananya      Rao  21.0   92.0  30000.0     Ananya Rao
2    NaN       NaN      NaN   NaN    NaN      NaN            NaN
3  104.0     Nisha  D'Souza  20.0   88.0  25000.0  Nisha D'Souza
4    NaN       NaN      NaN   NaN    NaN      NaN            NaN
5  106.0    Shreya   Shetty  19.0   95.0  30000.0  Shreya Shetty
6    NaN       NaN      NaN   NaN    NaN      NaN            NaN
7  108.0   Deepika     Bhat  20.0   81.0  28000.0   Deepika Bhat
8    NaN       NaN      NaN   NaN    NaN      NaN            NaN
9  110.0     Pooja      Rai  19.0   90.0  30000.0      Pooja Rai

In [20]:
sdata.loc[sdata['marks']>=85,"Result"]="Selected"
sdata.loc[sdata['marks']<85,"Result"]=" Not Selected"
sdata

C:\Users\91805\AppData\Local\Temp\ipykernel_15212\2718622647.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value 'Selected' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  sdata.loc[sdata['marks']>=85,"Result"]="Selected"

    id firstName  lastName  age  marks   fees         FullName         Result
0  101    Akshay    Shetty   20     85  25000    Akshay Shetty       Selected
1  102    Ananya       Rao   21     92  30000       Ananya Rao       Selected
2  103     Rohit  Bhandary   19     76  28000   Rohit Bhandary   Not Selected
3  104     Nisha   D'Souza   20     88  25000    Nisha D'Souza       Selected
4  105   Karthik   Poojary   22     69  32000  Karthik Poojary   Not Selected
5  106    Shreya    Shetty   19     95  30000    Shreya Shetty       Selected
6  107     Rohan      Naik   21     72  27000       Rohan Naik   Not Selected
7  108   Deepika      Bhat   20     81  28000     Deepika Bhat   Not Selected
8  109  Abhishek    Kotian   22     64  26000  Abhishek Kotian   Not Selected
9  110     Pooja       Rai   19     90  30000        Pooja Rai       Selected

In [24]:
sdata = pd.read_csv(r"C:\datascience\datascience-with-python\Pandas\student.csv")
 #give 10% discount to every student
n=int(input())
sdata["After 10% discount: "]=sdata["fees"]-(sdata['fees']*n)/100
sdata

 25

    id firstName  lastName  age  marks   fees  After 10% discount:
0  101    Akshay    Shetty   20     85  25000               18750.0
1  102    Ananya       Rao   21     92  30000               22500.0
2  103     Rohit  Bhandary   19     76  28000               21000.0
3  104     Nisha   D'Souza   20     88  25000               18750.0
4  105   Karthik   Poojary   22     69  32000               24000.0
5  106    Shreya    Shetty   19     95  30000               22500.0
6  107     Rohan      Naik   21     72  27000               20250.0
7  108   Deepika      Bhat   20     81  28000               21000.0
8  109  Abhishek    Kotian   22     64  26000               19500.0
9  110     Pooja       Rai   19     90  30000               22500.0